[package]
name = "yim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
serde = "1.0.197"
smallvec = "1.13.1"

[[bin]]
name = "yim"
